Audits: {Avg Ball Time: '0:32', Avg Extra Balls: 0, Avg Game Time: '1:42', Avg Score: 1790175,
  Balls Played: 3, Games Played: 1, Games Started: 827}
ClassicHighScores:
- {inits: AAA, score: 500}
- {inits: BBB, score: 600}
- {inits: CCC, score: 700}
- {inits: DDD, score: 800}
- {inits: EEE, score: 900}
