Audits:
  Avg Ball Time: 0:00
  Avg Extra Balls: 0
  Avg Game Time: 0:00
  Avg Score: 0
  Games Played: 0
  Games Started: 0
  Balls Played: 0
ClassicHighScores:
  - {inits: AAA, score: 900000000}
  - {inits: BBB, score: 800000000}
  - {inits: CCC, score: 700000000}
  - {inits: DDD, score: 600000000}
  - {inits: EEE, score: 500000000}
