Audits: {Avg Ball Time: '0:08', Avg Extra Balls: 0, Avg Game Time: '3:07', Avg Score: 5338500,
  Balls Played: 1371, Games Played: 457, Games Started: 470}
ClassicHighScores:
- {inits: AAA, score: 900000000}
- {inits: BBB, score: 800000000}
- {inits: CCC, score: 700000000}
- {inits: DDD, score: 600000000}
- {inits: EEE, score: 500000000}
