Audits: {Avg Ball Time: '0:00', Avg Extra Balls: 0, Avg Game Time: '0:00', Avg Score: 0,
  Balls Played: 0, Games Played: 0, Games Started: 615}
ClassicHighScores:
- {inits: AAA, score: 500}
- {inits: BBB, score: 600}
- {inits: CCC, score: 700}
- {inits: DDD, score: 800}
- {inits: EEE, score: 900}
