Audits: {Avg Ball Time: '0:25', Avg Extra Balls: 0, Avg Game Time: '2:37', Avg Score: 39478449,
  Balls Played: 20, Games Played: 7, Games Started: 859}
ClassicHighScores:
- {date: 'Sun Oct  9 13:52:48 2016', inits: XXYYYYYZ, score: 302109480}
- {date: 'Sun Oct  9 15:23:11 2016', inits: AAAAAAAAAA, score: 4605680}
- {date: 'Sun Oct  9 14:13:17 2016', inits: YYYXWVUTTT, score: 1554830}
- {date: 'Sun Oct  9 10:37:39 2016', inits: DDDDDDDDDD, score: 1145440}
- {date: 'Sun Oct  9 10:37:39 2016', inits: EEE, score: 900}
