ScoreLayout:       
    SinglePlayer:
        Score:
            visible: True# don't make this invisible...
            font: main_score
            font_style: gold
            h_justify: center
            v_justify: center
            x:  0.5
            y: 0.45
        CreditIndicator:                  
            visible: True # toggle this to False to make this invisible
            format: FREE PLAY
            font: score_sub
            font_style: 
                interior_color: [192, 192, 96]
                line_width: 1
                line_color: [128, 128, 0]
            x:  0.99 # values can be 0.0 to 1.0 as percentage of display
            y: 820 # whole numbers are taken as literal X-Y dimensions
            h_justify: right     # the text will be positioned on a point
            v_justify: bottom   # relative to the justification
        BallNumber:
            visible: True # toggle this to False to make this invisible
            format: BALL _
            font: score_sub
            font_style: 
                interior_color: [192, 192, 96]
                line_width: 1
                line_color: [128, 128, 0]
            h_justify: left
            v_justify: bottom
            x:  0.01
            y: 820
        Background: 
            Animation: 
                Name: clouds_1
    MultiPlayer:
        Background: # if omitted here, Singleplayer value is used.  Set to None to disable
            Animation: 
                Name: clouds_1
        Foreground: None # set to None to disable
        # CreditIndicator: # if you define these here too, they replace the others
        # BallNumber:   # as above
        ActivePlayer:
            font: main_score
            font_style: gold
            in_place_if_active: False
            h_justify: center
            v_justify: center
            x:  0.5
            y: 0.45
        PlayerOne:
            font: score_sub
            font_style: grey
            h_justify: left
            v_justify: top
            x: 0.01 
            y: 0
        PlayerTwo:
            font: score_sub
            font_style: grey
            h_justify: right
            v_justify: top
            x: 0.99
            y: 0
        PlayerThree:
            font: score_sub
            font_style: grey
            h_justify: left
            v_justify: 0.9
            x: 0.01
            y: 0.70 
        PlayerFour:
            font: score_sub
            font_style: grey
            h_justify: right
            v_justify: 0.9
            x: 0.99
            y: 0.70
